version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

  gotenberg:
    image: gotenberg/gotenberg:7.5.3
    networks:
      - hmpps_int
    container_name: gotenberg
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
    command:
      - "gotenberg"
      - "--api-port=3001"  
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--libreoffice-disable-routes=true"
      - "--pdfengines-engines=pdftk"
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/health' ]

networks:
  hmpps_int:
