version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

  gotenberg:
    image: gotenberg/gotenberg:7
    networks:
      - hmpps_int
    container_name: gotenberg
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3001"
    environment:
      - GOOGLE_CHROME_IGNORE_CERTIFICATE_ERRORS=1
      - DISABLE_UNOCONV=1
      - DEFAULT_WAIT_TIMEOUT=30
      - DEFAULT_LISTEN_PORT=3001
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/health' ]

networks:
  hmpps_int:
