import adjudicationUrls from '../../server/utils/urlGenerator'
import Page from '../pages/page'
import DataInsightsPage from '../pages/dataInsights'
import { ChartDetailsResult } from '../../server/services/ChartDetailsResult'

context('Adjudication data', () => {
  beforeEach(() => {
    cy.task('reset')
    cy.task('stubSignIn')
    cy.task('stubAuthUser')

    const chartEntries = getChartEntriesMap()

    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '1a',
      response: {
        agencyId: 'MDI',
        chartName: '1a',
        chartEntries: chartEntries['1a'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '1b',
      response: {
        agencyId: 'MDI',
        chartName: '1b',
        chartEntries: chartEntries['1b'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '1c',
      response: {
        agencyId: 'MDI',
        chartName: '1c',
        chartEntries: chartEntries['1c'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '1d',
      response: {
        agencyId: 'MDI',
        chartName: '1d',
        chartEntries: chartEntries['1d'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '1f',
      response: {
        agencyId: 'MDI',
        chartName: '1f',
        chartEntries: chartEntries['1f'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '2a',
      response: {
        agencyId: 'MDI',
        chartName: '2a',
        chartEntries: chartEntries['2a'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '2b',
      response: {
        agencyId: 'MDI',
        chartName: '2b',
        chartEntries: chartEntries['2b'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '3a',
      response: {
        agencyId: 'MDI',
        chartName: '3a',
        chartEntries: chartEntries['3a'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '3b',
      response: {
        agencyId: 'MDI',
        chartName: '3b',
        chartEntries: chartEntries['3b'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '5a',
      response: {
        agencyId: 'MDI',
        chartName: '5a',
        chartEntries: chartEntries['5a'],
      } as ChartDetailsResult,
    })
    cy.task('stubGetDataInsightsChart', {
      agencyId: 'MDI',
      chartName: '5b',
      response: {
        agencyId: 'MDI',
        chartName: '5b',
        chartEntries: chartEntries['5b'],
      } as ChartDetailsResult,
    })
    cy.signIn()
  })

  it('should contain the required page elements on /data-insights', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.start())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
  })

  it('should contain the required page elements /data-insights/totals-adjudications-and-locations', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.totalsAdjudicationsAndLocations())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
    page.checkChartTitle('Total adjudications - over 24 months (1a)')
    page.checkChartTitle('Total adjudications referred to independent adjudicator - over 24 months (1b)')
    page.checkChartTitle('Number of people with an adjudication in the past 30 days (1c)')
    page.checkChartTitle('Total adjudications by location of adjudication offence – last 30 days (1d)')
    page.checkChartTitle('Total adjudications by residential location of offender – last 30 days (1f)')
  })

  it('should contain the required page elements /data-insights/protected-characteristics-and-vulnerabilities', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.protectedCharacteristicsAndVulnerabilities())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
    page.checkChartTitle('Percentage and number of prisoners in the establishment currently (2a)')
    page.checkChartTitle(
      'Percentage and number of prisoners with an adjudication by protected characteristic or vulnerability – last 30 days (2b)'
    )
  })

  it('should contain the required page elements /data-insights/offence-type', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.offenceType())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
    page.checkChartTitle('Adjudication offence type by location – last 30 days (3b)')
  })

  it('should contain the required page elements /data-insights/punishments', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.punishments())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
  })

  it('should contain the required page elements /data-insights/pleas-and-findings', () => {
    cy.visit(adjudicationUrls.dataInsights.urls.pleasAndFindings())
    const page: DataInsightsPage = Page.verifyOnPage(DataInsightsPage)
    page.checkOnPage()
    page.checkChartTitle('Pleas given – current month and previous 12 months (5a)')
    page.checkChartTitle('Total adjudications by findings – current month and previous 12 months (5b)')
  })
})

const getChartEntriesMap = () => {
  const chartEntries1a = [
    {
      month: 8.0,
      year_curr: 2022.0,
      count_curr: 17.0,
      year_prev: 2021.0,
      count_prev: 11.0,
    },
    {
      month: 9.0,
      year_curr: 2022.0,
      count_curr: 28.0,
      year_prev: 2021.0,
      count_prev: 79.0,
    },
    {
      month: 10.0,
      year_curr: 2022.0,
      count_curr: 76.0,
      year_prev: 2021.0,
      count_prev: 14.0,
    },
    {
      month: 11.0,
      year_curr: 2022.0,
      count_curr: 85.0,
      year_prev: 2021.0,
      count_prev: 43.0,
    },
    {
      month: 12.0,
      year_curr: 2022.0,
      count_curr: 42.0,
      year_prev: 2021.0,
      count_prev: 64.0,
    },
    {
      month: 1.0,
      year_curr: 2023.0,
      count_curr: 77.0,
      year_prev: 2022.0,
      count_prev: 7.0,
    },
    {
      month: 2.0,
      year_curr: 2023.0,
      count_curr: 42.0,
      year_prev: 2022.0,
      count_prev: 78.0,
    },
    {
      month: 3.0,
      year_curr: 2023.0,
      count_curr: 89.0,
      year_prev: 2022.0,
      count_prev: 9.0,
    },
    {
      month: 4.0,
      year_curr: 2023.0,
      count_curr: 59.0,
      year_prev: 2022.0,
      count_prev: 77.0,
    },
    {
      month: 5.0,
      year_curr: 2023.0,
      count_curr: 48.0,
      year_prev: 2022.0,
      count_prev: 95.0,
    },
    {
      month: 6.0,
      year_curr: 2023.0,
      count_curr: 1.0,
      year_prev: 2022.0,
      count_prev: 84.0,
    },
    {
      month: 7.0,
      year_curr: 2023.0,
      count_curr: 97.0,
      year_prev: 2022.0,
      count_prev: 54.0,
    },
  ]
  const chartEntries1b = [
    {
      month: 8.0,
      year_curr: 2022.0,
      count_curr: 88.0,
      year_prev: 2021.0,
      count_prev: 31.0,
    },
    {
      month: 9.0,
      year_curr: 2022.0,
      count_curr: 16.0,
      year_prev: 2021.0,
      count_prev: 53.0,
    },
    {
      month: 10.0,
      year_curr: 2022.0,
      count_curr: 96.0,
      year_prev: 2021.0,
      count_prev: 87.0,
    },
    {
      month: 11.0,
      year_curr: 2022.0,
      count_curr: 52.0,
      year_prev: 2021.0,
      count_prev: 24.0,
    },
    {
      month: 12.0,
      year_curr: 2022.0,
      count_curr: 75.0,
      year_prev: 2021.0,
      count_prev: 19.0,
    },
    {
      month: 1.0,
      year_curr: 2023.0,
      count_curr: 4.0,
      year_prev: 2022.0,
      count_prev: 74.0,
    },
    {
      month: 2.0,
      year_curr: 2023.0,
      count_curr: 91.0,
      year_prev: 2022.0,
      count_prev: 35.0,
    },
    {
      month: 3.0,
      year_curr: 2023.0,
      count_curr: 78.0,
      year_prev: 2022.0,
      count_prev: 54.0,
    },
    {
      month: 4.0,
      year_curr: 2023.0,
      count_curr: 1.0,
      year_prev: 2022.0,
      count_prev: 78.0,
    },
    {
      month: 5.0,
      year_curr: 2023.0,
      count_curr: 61.0,
      year_prev: 2022.0,
      count_prev: 80.0,
    },
    {
      month: 6.0,
      year_curr: 2023.0,
      count_curr: 12.0,
      year_prev: 2022.0,
      count_prev: 81.0,
    },
    {
      month: 7.0,
      year_curr: 2023.0,
      count_curr: 1.0,
      year_prev: 2022.0,
      count_prev: 67.0,
    },
  ]
  const chartEntries1c = [
    {
      count: 13.0,
      proportion: 0.27,
    },
  ]
  const chartEntries1d = [
    {
      incident_loc: 'Wing A',
      count: 86.0,
      proportion: 0.41,
    },
    {
      incident_loc: 'Wing B',
      count: 80.0,
      proportion: 0.38,
    },
    {
      incident_loc: 'Wing C',
      count: 45.0,
      proportion: 0.21,
    },
  ]
  const chartEntries1f = [
    {
      wing_loc: 'Wing B',
      count: 76.0,
      proportion: 0.59,
    },
    {
      wing_loc: 'Wing A',
      count: 36.0,
      proportion: 0.28,
    },
    {
      wing_loc: 'Wing C',
      count: 16.0,
      proportion: 0.12,
    },
  ]
  const chartEntries2a = [
    {
      characteristic: 'Age',
      value: '15-17',
      count: 46.0,
      proportion: 0.01,
    },
    {
      characteristic: 'Age',
      value: '18-25',
      count: 79.0,
      proportion: 0.05,
    },
    {
      characteristic: 'Age',
      value: '26-35',
      count: 91.0,
      proportion: 0.02,
    },
    {
      characteristic: 'Age',
      value: '36-45',
      count: 14.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Age',
      value: '46-55',
      count: 13.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Age',
      value: '56-65',
      count: 83.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Age',
      value: '66+',
      count: 55.0,
      proportion: 0.06,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Asian or Asian British',
      count: 77.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Black or Black British',
      count: 23.0,
      proportion: 0.1,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Mixed',
      count: 81.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Other',
      count: 6.0,
      proportion: 0.06,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Unknown',
      count: 95.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Ethnicity',
      value: 'White',
      count: 90.0,
      proportion: 0.04,
    },
    {
      characteristic: 'Learning disability',
      value: 'No',
      count: 57.0,
      proportion: 0.04,
    },
    {
      characteristic: 'Learning disability',
      value: 'Yes',
      count: 5.0,
      proportion: 0.08,
    },
    {
      characteristic: 'Maturity',
      value: '0.0',
      count: 36.0,
      proportion: 0.03,
    },
    {
      characteristic: 'Maturity',
      value: '1.0',
      count: 19.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Maturity',
      value: 'Unknown',
      count: 89.0,
      proportion: 0.06,
    },
    {
      characteristic: 'Recorded disability',
      value: 'No recorded disability',
      count: 61.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Recorded disability',
      value: 'Recorded disability',
      count: 77.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Recorded disability',
      value: 'Unknown',
      count: 41.0,
      proportion: 0.1,
    },
    {
      characteristic: 'Religion',
      value: 'Buddhist',
      count: 33.0,
      proportion: 0.0,
    },
    {
      characteristic: 'Religion',
      value: 'Christian',
      count: 19.0,
      proportion: 0.02,
    },
    {
      characteristic: 'Religion',
      value: 'Hindu',
      count: 75.0,
      proportion: 0.08,
    },
    {
      characteristic: 'Religion',
      value: 'Jewish',
      count: 44.0,
      proportion: 0.02,
    },
    {
      characteristic: 'Religion',
      value: 'Muslim',
      count: 40.0,
      proportion: 0.06,
    },
    {
      characteristic: 'Religion',
      value: 'No religion',
      count: 85.0,
      proportion: 0.0,
    },
    {
      characteristic: 'Religion',
      value: 'Other',
      count: 20.0,
      proportion: 0.01,
    },
    {
      characteristic: 'Religion',
      value: 'Sikh',
      count: 84.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Religion',
      value: 'Unkown',
      count: 33.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Bisexual',
      count: 25.0,
      proportion: 0.09,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Heterosexual',
      count: 97.0,
      proportion: 0.01,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Homosexual',
      count: 48.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Other',
      count: 75.0,
      proportion: 0.03,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Unknown',
      count: 97.0,
      proportion: 0.04,
    },
  ]
  const chartEntries2b = [
    {
      characteristic: 'Age',
      value: '15-17',
      count: 26.0,
      proportion: 0.04,
    },
    {
      characteristic: 'Age',
      value: '18-25',
      count: 92.0,
      proportion: 0.15,
    },
    {
      characteristic: 'Age',
      value: '26-35',
      count: 97.0,
      proportion: 0.16,
    },
    {
      characteristic: 'Age',
      value: '36-45',
      count: 78.0,
      proportion: 0.13,
    },
    {
      characteristic: 'Age',
      value: '46-55',
      count: 41.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Age',
      value: '56-65',
      count: 97.0,
      proportion: 0.16,
    },
    {
      characteristic: 'Age',
      value: '66+',
      count: 89.0,
      proportion: 0.15,
    },
    {
      characteristic: 'Age',
      value: 'Unknown',
      count: 77.0,
      proportion: 0.13,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Asian or Asian British',
      count: 31.0,
      proportion: 0.1,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Black or Black British',
      count: 51.0,
      proportion: 0.17,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Mixed',
      count: 78.0,
      proportion: 0.25,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Other',
      count: 43.0,
      proportion: 0.14,
    },
    {
      characteristic: 'Ethnicity',
      value: 'Unknown',
      count: 15.0,
      proportion: 0.05,
    },
    {
      characteristic: 'Ethnicity',
      value: 'White',
      count: 89.0,
      proportion: 0.29,
    },
    {
      characteristic: 'Learning disability',
      value: 'No',
      count: 16.0,
      proportion: 0.32,
    },
    {
      characteristic: 'Learning disability',
      value: 'Yes',
      count: 34.0,
      proportion: 0.68,
    },
    {
      characteristic: 'Maturity',
      value: '0.0',
      count: 2.0,
      proportion: 0.02,
    },
    {
      characteristic: 'Maturity',
      value: '1.0',
      count: 95.0,
      proportion: 0.77,
    },
    {
      characteristic: 'Maturity',
      value: 'Unknown',
      count: 26.0,
      proportion: 0.21,
    },
    {
      characteristic: 'Recorded disability',
      value: 'No recorded disability',
      count: 14.0,
      proportion: 0.12,
    },
    {
      characteristic: 'Recorded disability',
      value: 'Recorded disability',
      count: 54.0,
      proportion: 0.46,
    },
    {
      characteristic: 'Recorded disability',
      value: 'Unknown',
      count: 49.0,
      proportion: 0.42,
    },
    {
      characteristic: 'Religion',
      value: 'Buddhist',
      count: 86.0,
      proportion: 0.21,
    },
    {
      characteristic: 'Religion',
      value: 'Christian',
      count: 12.0,
      proportion: 0.03,
    },
    {
      characteristic: 'Religion',
      value: 'Hindu',
      count: 77.0,
      proportion: 0.19,
    },
    {
      characteristic: 'Religion',
      value: 'Jewish',
      count: 86.0,
      proportion: 0.21,
    },
    {
      characteristic: 'Religion',
      value: 'Muslim',
      count: 2.0,
      proportion: 0.0,
    },
    {
      characteristic: 'Religion',
      value: 'No religion',
      count: 53.0,
      proportion: 0.13,
    },
    {
      characteristic: 'Religion',
      value: 'Other',
      count: 15.0,
      proportion: 0.04,
    },
    {
      characteristic: 'Religion',
      value: 'Sikh',
      count: 68.0,
      proportion: 0.17,
    },
    {
      characteristic: 'Religion',
      value: 'Unknown',
      count: 4.0,
      proportion: 0.01,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Bisexual',
      count: 18.0,
      proportion: 0.07,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Heterosexual',
      count: 68.0,
      proportion: 0.28,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Homosexual',
      count: 46.0,
      proportion: 0.19,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Other',
      count: 40.0,
      proportion: 0.17,
    },
    {
      characteristic: 'Sexual orientation',
      value: 'Unknown',
      count: 70.0,
      proportion: 0.29,
    },
  ]
  const chartEntries3a = [
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 7.0,
      year: 2022.0,
      count: 88.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 8.0,
      year: 2022.0,
      count: 46.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 9.0,
      year: 2022.0,
      count: 62.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 10.0,
      year: 2022.0,
      count: 0.0,
      proportion: 0.0,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 11.0,
      year: 2022.0,
      count: 10.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 12.0,
      year: 2022.0,
      count: 1.0,
      proportion: 0.0,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 1.0,
      year: 2023.0,
      count: 73.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 2.0,
      year: 2023.0,
      count: 2.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 3.0,
      year: 2023.0,
      count: 4.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 4.0,
      year: 2023.0,
      count: 89.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 5.0,
      year: 2023.0,
      count: 48.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 6.0,
      year: 2023.0,
      count: 57.0,
      proportion: 0.12,
    },
    {
      offence_type: 'Arson or damage to the prison or property',
      month: 7.0,
      year: 2023.0,
      count: 3.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 7.0,
      year: 2022.0,
      count: 32.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 8.0,
      year: 2022.0,
      count: 50.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 9.0,
      year: 2022.0,
      count: 70.0,
      proportion: 0.12,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 10.0,
      year: 2022.0,
      count: 62.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 11.0,
      year: 2022.0,
      count: 26.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 12.0,
      year: 2022.0,
      count: 28.0,
      proportion: 0.07,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 1.0,
      year: 2023.0,
      count: 14.0,
      proportion: 0.03,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 2.0,
      year: 2023.0,
      count: 53.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 3.0,
      year: 2023.0,
      count: 5.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 4.0,
      year: 2023.0,
      count: 40.0,
      proportion: 0.07,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 5.0,
      year: 2023.0,
      count: 83.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 6.0,
      year: 2023.0,
      count: 80.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      month: 7.0,
      year: 2023.0,
      count: 19.0,
      proportion: 0.04,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 7.0,
      year: 2022.0,
      count: 93.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 8.0,
      year: 2022.0,
      count: 67.0,
      proportion: 0.12,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 9.0,
      year: 2022.0,
      count: 58.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 10.0,
      year: 2022.0,
      count: 62.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 11.0,
      year: 2022.0,
      count: 83.0,
      proportion: 0.19,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 12.0,
      year: 2022.0,
      count: 42.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 1.0,
      year: 2023.0,
      count: 10.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 2.0,
      year: 2023.0,
      count: 58.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 3.0,
      year: 2023.0,
      count: 82.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 4.0,
      year: 2023.0,
      count: 55.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 5.0,
      year: 2023.0,
      count: 99.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 6.0,
      year: 2023.0,
      count: 70.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      month: 7.0,
      year: 2023.0,
      count: 85.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Detains another person',
      month: 7.0,
      year: 2022.0,
      count: 57.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Detains another person',
      month: 8.0,
      year: 2022.0,
      count: 99.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Detains another person',
      month: 9.0,
      year: 2022.0,
      count: 84.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Detains another person',
      month: 10.0,
      year: 2022.0,
      count: 73.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Detains another person',
      month: 11.0,
      year: 2022.0,
      count: 24.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Detains another person',
      month: 12.0,
      year: 2022.0,
      count: 17.0,
      proportion: 0.04,
    },
    {
      offence_type: 'Detains another person',
      month: 1.0,
      year: 2023.0,
      count: 73.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Detains another person',
      month: 2.0,
      year: 2023.0,
      count: 50.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Detains another person',
      month: 3.0,
      year: 2023.0,
      count: 78.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Detains another person',
      month: 4.0,
      year: 2023.0,
      count: 13.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Detains another person',
      month: 5.0,
      year: 2023.0,
      count: 31.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Detains another person',
      month: 6.0,
      year: 2023.0,
      count: 37.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Detains another person',
      month: 7.0,
      year: 2023.0,
      count: 79.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 7.0,
      year: 2022.0,
      count: 49.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 8.0,
      year: 2022.0,
      count: 26.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 9.0,
      year: 2022.0,
      count: 78.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 10.0,
      year: 2022.0,
      count: 77.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 11.0,
      year: 2022.0,
      count: 89.0,
      proportion: 0.2,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 12.0,
      year: 2022.0,
      count: 62.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 1.0,
      year: 2023.0,
      count: 94.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 2.0,
      year: 2023.0,
      count: 35.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 3.0,
      year: 2023.0,
      count: 58.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 4.0,
      year: 2023.0,
      count: 39.0,
      proportion: 0.07,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 5.0,
      year: 2023.0,
      count: 31.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 6.0,
      year: 2023.0,
      count: 11.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      month: 7.0,
      year: 2023.0,
      count: 42.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 7.0,
      year: 2022.0,
      count: 26.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 8.0,
      year: 2022.0,
      count: 63.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 9.0,
      year: 2022.0,
      count: 47.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 10.0,
      year: 2022.0,
      count: 68.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 11.0,
      year: 2022.0,
      count: 35.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 12.0,
      year: 2022.0,
      count: 37.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 1.0,
      year: 2023.0,
      count: 82.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 2.0,
      year: 2023.0,
      count: 66.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 3.0,
      year: 2023.0,
      count: 74.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 4.0,
      year: 2023.0,
      count: 54.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 5.0,
      year: 2023.0,
      count: 46.0,
      proportion: 0.08,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 6.0,
      year: 2023.0,
      count: 49.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      month: 7.0,
      year: 2023.0,
      count: 32.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 7.0,
      year: 2022.0,
      count: 83.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 8.0,
      year: 2022.0,
      count: 26.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 9.0,
      year: 2022.0,
      count: 1.0,
      proportion: 0.0,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 10.0,
      year: 2022.0,
      count: 11.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 11.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.09,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 12.0,
      year: 2022.0,
      count: 61.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 1.0,
      year: 2023.0,
      count: 81.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 2.0,
      year: 2023.0,
      count: 79.0,
      proportion: 0.2,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 3.0,
      year: 2023.0,
      count: 0.0,
      proportion: 0.0,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 4.0,
      year: 2023.0,
      count: 68.0,
      proportion: 0.12,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 5.0,
      year: 2023.0,
      count: 87.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 6.0,
      year: 2023.0,
      count: 12.0,
      proportion: 0.03,
    },
    {
      offence_type: 'Escape or failure to comply with temporary release conditions',
      month: 7.0,
      year: 2023.0,
      count: 96.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 7.0,
      year: 2022.0,
      count: 13.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 8.0,
      year: 2022.0,
      count: 87.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 9.0,
      year: 2022.0,
      count: 97.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 10.0,
      year: 2022.0,
      count: 71.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 11.0,
      year: 2022.0,
      count: 4.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 12.0,
      year: 2022.0,
      count: 19.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 1.0,
      year: 2023.0,
      count: 64.0,
      proportion: 0.12,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 2.0,
      year: 2023.0,
      count: 41.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 3.0,
      year: 2023.0,
      count: 93.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 4.0,
      year: 2023.0,
      count: 97.0,
      proportion: 0.17,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 5.0,
      year: 2023.0,
      count: 28.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 6.0,
      year: 2023.0,
      count: 85.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      month: 7.0,
      year: 2023.0,
      count: 86.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 7.0,
      year: 2022.0,
      count: 58.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 8.0,
      year: 2022.0,
      count: 6.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 9.0,
      year: 2022.0,
      count: 1.0,
      proportion: 0.0,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 10.0,
      year: 2022.0,
      count: 49.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 11.0,
      year: 2022.0,
      count: 55.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 12.0,
      year: 2022.0,
      count: 50.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 1.0,
      year: 2023.0,
      count: 8.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 2.0,
      year: 2023.0,
      count: 10.0,
      proportion: 0.03,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 3.0,
      year: 2023.0,
      count: 91.0,
      proportion: 0.18,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 4.0,
      year: 2023.0,
      count: 40.0,
      proportion: 0.07,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 5.0,
      year: 2023.0,
      count: 66.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 6.0,
      year: 2023.0,
      count: 49.0,
      proportion: 0.1,
    },
    {
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      month: 7.0,
      year: 2023.0,
      count: 71.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Unknown',
      month: 7.0,
      year: 2022.0,
      count: 33.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Unknown',
      month: 8.0,
      year: 2022.0,
      count: 82.0,
      proportion: 0.15,
    },
    {
      offence_type: 'Unknown',
      month: 9.0,
      year: 2022.0,
      count: 83.0,
      proportion: 0.14,
    },
    {
      offence_type: 'Unknown',
      month: 10.0,
      year: 2022.0,
      count: 9.0,
      proportion: 0.02,
    },
    {
      offence_type: 'Unknown',
      month: 11.0,
      year: 2022.0,
      count: 70.0,
      proportion: 0.16,
    },
    {
      offence_type: 'Unknown',
      month: 12.0,
      year: 2022.0,
      count: 75.0,
      proportion: 0.19,
    },
    {
      offence_type: 'Unknown',
      month: 1.0,
      year: 2023.0,
      count: 29.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Unknown',
      month: 2.0,
      year: 2023.0,
      count: 4.0,
      proportion: 0.01,
    },
    {
      offence_type: 'Unknown',
      month: 3.0,
      year: 2023.0,
      count: 29.0,
      proportion: 0.06,
    },
    {
      offence_type: 'Unknown',
      month: 4.0,
      year: 2023.0,
      count: 77.0,
      proportion: 0.13,
    },
    {
      offence_type: 'Unknown',
      month: 5.0,
      year: 2023.0,
      count: 63.0,
      proportion: 0.11,
    },
    {
      offence_type: 'Unknown',
      month: 6.0,
      year: 2023.0,
      count: 23.0,
      proportion: 0.05,
    },
    {
      offence_type: 'Unknown',
      month: 7.0,
      year: 2023.0,
      count: 23.0,
      proportion: 0.04,
    },
  ]
  const chartEntries3b = [
    {
      incident_loc: 'Wing B',
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      count: 98.0,
      proportion: 0.06,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      count: 98.0,
      proportion: 0.06,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      count: 96.0,
      proportion: 0.06,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      count: 95.0,
      proportion: 0.06,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Escape or failure to comply with temporary release conditions',
      count: 90.0,
      proportion: 0.05,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      count: 85.0,
      proportion: 0.05,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Escape or failure to comply with temporary release conditions',
      count: 83.0,
      proportion: 0.05,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      count: 82.0,
      proportion: 0.05,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      count: 82.0,
      proportion: 0.05,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Assault, fighting, or endangering the health or personal safety of others',
      count: 70.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Arson or damage to the prison or property',
      count: 69.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Unknown',
      count: 68.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Escape or failure to comply with temporary release conditions',
      count: 64.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      count: 63.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Arson or damage to the prison or property',
      count: 62.0,
      proportion: 0.04,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Possession of unauthorised articles, or drugs or alcohol related',
      count: 54.0,
      proportion: 0.03,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Unknown',
      count: 51.0,
      proportion: 0.03,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Arson or damage to the prison or property',
      count: 48.0,
      proportion: 0.03,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      count: 45.0,
      proportion: 0.03,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Unknown',
      count: 41.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Disrespectful, threatening, abusive, or insulting behaviour',
      count: 40.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      count: 40.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Disobeys any lawful order, or failure to comply with any rule or regulation',
      count: 36.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Detains another person',
      count: 33.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      count: 32.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Detains another person',
      count: 26.0,
      proportion: 0.02,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Detains another person',
      count: 19.0,
      proportion: 0.01,
    },
    {
      incident_loc: 'Wing C',
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      count: 19.0,
      proportion: 0.01,
    },
    {
      incident_loc: 'Wing A',
      offence_type: 'Stopping someone who is not a prisoner from doing their job',
      count: 2.0,
      proportion: 0.0,
    },
    {
      incident_loc: 'Wing B',
      offence_type: 'Being absent without authorisation, being in an unauthorised place, or failing to work correctly',
      count: 0.0,
      proportion: 0.0,
    },
  ]
  const chartEntries5a = [
    {
      plea: 'Guilty',
      month: 7.0,
      year: 2022.0,
      count: 52.0,
      proportion: 0.29,
    },
    {
      plea: 'Guilty',
      month: 8.0,
      year: 2022.0,
      count: 87.0,
      proportion: 0.3,
    },
    {
      plea: 'Guilty',
      month: 9.0,
      year: 2022.0,
      count: 35.0,
      proportion: 0.23,
    },
    {
      plea: 'Guilty',
      month: 10.0,
      year: 2022.0,
      count: 15.0,
      proportion: 0.05,
    },
    {
      plea: 'Guilty',
      month: 11.0,
      year: 2022.0,
      count: 11.0,
      proportion: 0.08,
    },
    {
      plea: 'Guilty',
      month: 12.0,
      year: 2022.0,
      count: 52.0,
      proportion: 0.19,
    },
    {
      plea: 'Guilty',
      month: 1.0,
      year: 2023.0,
      count: 50.0,
      proportion: 0.16,
    },
    {
      plea: 'Guilty',
      month: 2.0,
      year: 2023.0,
      count: 94.0,
      proportion: 0.36,
    },
    {
      plea: 'Guilty',
      month: 3.0,
      year: 2023.0,
      count: 12.0,
      proportion: 0.07,
    },
    {
      plea: 'Guilty',
      month: 4.0,
      year: 2023.0,
      count: 94.0,
      proportion: 0.35,
    },
    {
      plea: 'Guilty',
      month: 5.0,
      year: 2023.0,
      count: 21.0,
      proportion: 0.11,
    },
    {
      plea: 'Guilty',
      month: 6.0,
      year: 2023.0,
      count: 35.0,
      proportion: 0.14,
    },
    {
      plea: 'Guilty',
      month: 7.0,
      year: 2023.0,
      count: 97.0,
      proportion: 0.35,
    },
    {
      plea: 'Not Asked',
      month: 7.0,
      year: 2022.0,
      count: 91.0,
      proportion: 0.5,
    },
    {
      plea: 'Not Asked',
      month: 8.0,
      year: 2022.0,
      count: 34.0,
      proportion: 0.12,
    },
    {
      plea: 'Not Asked',
      month: 9.0,
      year: 2022.0,
      count: 17.0,
      proportion: 0.11,
    },
    {
      plea: 'Not Asked',
      month: 10.0,
      year: 2022.0,
      count: 48.0,
      proportion: 0.17,
    },
    {
      plea: 'Not Asked',
      month: 11.0,
      year: 2022.0,
      count: 24.0,
      proportion: 0.17,
    },
    {
      plea: 'Not Asked',
      month: 12.0,
      year: 2022.0,
      count: 59.0,
      proportion: 0.22,
    },
    {
      plea: 'Not Asked',
      month: 1.0,
      year: 2023.0,
      count: 60.0,
      proportion: 0.19,
    },
    {
      plea: 'Not Asked',
      month: 2.0,
      year: 2023.0,
      count: 28.0,
      proportion: 0.11,
    },
    {
      plea: 'Not Asked',
      month: 3.0,
      year: 2023.0,
      count: 31.0,
      proportion: 0.19,
    },
    {
      plea: 'Not Asked',
      month: 4.0,
      year: 2023.0,
      count: 36.0,
      proportion: 0.13,
    },
    {
      plea: 'Not Asked',
      month: 5.0,
      year: 2023.0,
      count: 35.0,
      proportion: 0.18,
    },
    {
      plea: 'Not Asked',
      month: 6.0,
      year: 2023.0,
      count: 43.0,
      proportion: 0.17,
    },
    {
      plea: 'Not Asked',
      month: 7.0,
      year: 2023.0,
      count: 54.0,
      proportion: 0.19,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 7.0,
      year: 2022.0,
      count: 11.0,
      proportion: 0.06,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 8.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.13,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 9.0,
      year: 2022.0,
      count: 69.0,
      proportion: 0.45,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 10.0,
      year: 2022.0,
      count: 54.0,
      proportion: 0.19,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 11.0,
      year: 2022.0,
      count: 10.0,
      proportion: 0.07,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 12.0,
      year: 2022.0,
      count: 60.0,
      proportion: 0.22,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 1.0,
      year: 2023.0,
      count: 59.0,
      proportion: 0.19,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 2.0,
      year: 2023.0,
      count: 27.0,
      proportion: 0.1,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 3.0,
      year: 2023.0,
      count: 38.0,
      proportion: 0.23,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 4.0,
      year: 2023.0,
      count: 15.0,
      proportion: 0.06,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 5.0,
      year: 2023.0,
      count: 48.0,
      proportion: 0.25,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 6.0,
      year: 2023.0,
      count: 51.0,
      proportion: 0.2,
    },
    {
      plea: 'Not Guilty Due to Refusal to Plea/Attend',
      month: 7.0,
      year: 2023.0,
      count: 41.0,
      proportion: 0.15,
    },
    {
      plea: 'Not guilty',
      month: 7.0,
      year: 2022.0,
      count: 8.0,
      proportion: 0.04,
    },
    {
      plea: 'Not guilty',
      month: 8.0,
      year: 2022.0,
      count: 90.0,
      proportion: 0.31,
    },
    {
      plea: 'Not guilty',
      month: 9.0,
      year: 2022.0,
      count: 6.0,
      proportion: 0.04,
    },
    {
      plea: 'Not guilty',
      month: 10.0,
      year: 2022.0,
      count: 98.0,
      proportion: 0.35,
    },
    {
      plea: 'Not guilty',
      month: 11.0,
      year: 2022.0,
      count: 13.0,
      proportion: 0.09,
    },
    {
      plea: 'Not guilty',
      month: 12.0,
      year: 2022.0,
      count: 27.0,
      proportion: 0.1,
    },
    {
      plea: 'Not guilty',
      month: 1.0,
      year: 2023.0,
      count: 92.0,
      proportion: 0.3,
    },
    {
      plea: 'Not guilty',
      month: 2.0,
      year: 2023.0,
      count: 40.0,
      proportion: 0.15,
    },
    {
      plea: 'Not guilty',
      month: 3.0,
      year: 2023.0,
      count: 48.0,
      proportion: 0.29,
    },
    {
      plea: 'Not guilty',
      month: 4.0,
      year: 2023.0,
      count: 67.0,
      proportion: 0.25,
    },
    {
      plea: 'Not guilty',
      month: 5.0,
      year: 2023.0,
      count: 8.0,
      proportion: 0.04,
    },
    {
      plea: 'Not guilty',
      month: 6.0,
      year: 2023.0,
      count: 87.0,
      proportion: 0.34,
    },
    {
      plea: 'Not guilty',
      month: 7.0,
      year: 2023.0,
      count: 36.0,
      proportion: 0.13,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 7.0,
      year: 2022.0,
      count: 20.0,
      proportion: 0.11,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 8.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.13,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 9.0,
      year: 2022.0,
      count: 25.0,
      proportion: 0.16,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 10.0,
      year: 2022.0,
      count: 67.0,
      proportion: 0.24,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 11.0,
      year: 2022.0,
      count: 81.0,
      proportion: 0.58,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 12.0,
      year: 2022.0,
      count: 72.0,
      proportion: 0.27,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 1.0,
      year: 2023.0,
      count: 50.0,
      proportion: 0.16,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 2.0,
      year: 2023.0,
      count: 70.0,
      proportion: 0.27,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 3.0,
      year: 2023.0,
      count: 37.0,
      proportion: 0.22,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 4.0,
      year: 2023.0,
      count: 60.0,
      proportion: 0.22,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 5.0,
      year: 2023.0,
      count: 80.0,
      proportion: 0.42,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 6.0,
      year: 2023.0,
      count: 42.0,
      proportion: 0.16,
    },
    {
      plea: 'Unfit to Plea or Attend',
      month: 7.0,
      year: 2023.0,
      count: 52.0,
      proportion: 0.19,
    },
  ]
  const chartEntries5b = [
    {
      finding: 'Charge Dismissed',
      month: 7.0,
      year: 2022.0,
      count: 12.0,
      proportion: 0.06,
    },
    {
      finding: 'Charge Dismissed',
      month: 8.0,
      year: 2022.0,
      count: 87.0,
      proportion: 0.32,
    },
    {
      finding: 'Charge Dismissed',
      month: 9.0,
      year: 2022.0,
      count: 54.0,
      proportion: 0.16,
    },
    {
      finding: 'Charge Dismissed',
      month: 10.0,
      year: 2022.0,
      count: 22.0,
      proportion: 0.07,
    },
    {
      finding: 'Charge Dismissed',
      month: 11.0,
      year: 2022.0,
      count: 31.0,
      proportion: 0.13,
    },
    {
      finding: 'Charge Dismissed',
      month: 12.0,
      year: 2022.0,
      count: 49.0,
      proportion: 0.27,
    },
    {
      finding: 'Charge Dismissed',
      month: 1.0,
      year: 2023.0,
      count: 82.0,
      proportion: 0.22,
    },
    {
      finding: 'Charge Dismissed',
      month: 2.0,
      year: 2023.0,
      count: 75.0,
      proportion: 0.21,
    },
    {
      finding: 'Charge Dismissed',
      month: 3.0,
      year: 2023.0,
      count: 95.0,
      proportion: 0.24,
    },
    {
      finding: 'Charge Dismissed',
      month: 4.0,
      year: 2023.0,
      count: 83.0,
      proportion: 0.31,
    },
    {
      finding: 'Charge Dismissed',
      month: 5.0,
      year: 2023.0,
      count: 22.0,
      proportion: 0.05,
    },
    {
      finding: 'Charge Dismissed',
      month: 6.0,
      year: 2023.0,
      count: 57.0,
      proportion: 0.26,
    },
    {
      finding: 'Charge Dismissed',
      month: 7.0,
      year: 2023.0,
      count: 71.0,
      proportion: 0.21,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 7.0,
      year: 2022.0,
      count: 27.0,
      proportion: 0.13,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 8.0,
      year: 2022.0,
      count: 74.0,
      proportion: 0.27,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 9.0,
      year: 2022.0,
      count: 69.0,
      proportion: 0.21,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 10.0,
      year: 2022.0,
      count: 60.0,
      proportion: 0.18,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 11.0,
      year: 2022.0,
      count: 62.0,
      proportion: 0.26,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 12.0,
      year: 2022.0,
      count: 1.0,
      proportion: 0.01,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 1.0,
      year: 2023.0,
      count: 56.0,
      proportion: 0.15,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 2.0,
      year: 2023.0,
      count: 32.0,
      proportion: 0.09,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 3.0,
      year: 2023.0,
      count: 45.0,
      proportion: 0.11,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 4.0,
      year: 2023.0,
      count: 64.0,
      proportion: 0.24,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 5.0,
      year: 2023.0,
      count: 88.0,
      proportion: 0.22,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 6.0,
      year: 2023.0,
      count: 29.0,
      proportion: 0.13,
    },
    {
      finding: 'Charge Not Proceeded With',
      month: 7.0,
      year: 2023.0,
      count: 72.0,
      proportion: 0.21,
    },
    {
      finding: 'Charge Proved',
      month: 7.0,
      year: 2022.0,
      count: 6.0,
      proportion: 0.03,
    },
    {
      finding: 'Charge Proved',
      month: 8.0,
      year: 2022.0,
      count: 49.0,
      proportion: 0.18,
    },
    {
      finding: 'Charge Proved',
      month: 9.0,
      year: 2022.0,
      count: 37.0,
      proportion: 0.11,
    },
    {
      finding: 'Charge Proved',
      month: 10.0,
      year: 2022.0,
      count: 15.0,
      proportion: 0.04,
    },
    {
      finding: 'Charge Proved',
      month: 11.0,
      year: 2022.0,
      count: 47.0,
      proportion: 0.2,
    },
    {
      finding: 'Charge Proved',
      month: 12.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.22,
    },
    {
      finding: 'Charge Proved',
      month: 1.0,
      year: 2023.0,
      count: 92.0,
      proportion: 0.25,
    },
    {
      finding: 'Charge Proved',
      month: 2.0,
      year: 2023.0,
      count: 48.0,
      proportion: 0.14,
    },
    {
      finding: 'Charge Proved',
      month: 3.0,
      year: 2023.0,
      count: 75.0,
      proportion: 0.19,
    },
    {
      finding: 'Charge Proved',
      month: 4.0,
      year: 2023.0,
      count: 20.0,
      proportion: 0.07,
    },
    {
      finding: 'Charge Proved',
      month: 5.0,
      year: 2023.0,
      count: 49.0,
      proportion: 0.12,
    },
    {
      finding: 'Charge Proved',
      month: 6.0,
      year: 2023.0,
      count: 40.0,
      proportion: 0.18,
    },
    {
      finding: 'Charge Proved',
      month: 7.0,
      year: 2023.0,
      count: 30.0,
      proportion: 0.09,
    },
    {
      finding: 'Quashed',
      month: 7.0,
      year: 2022.0,
      count: 56.0,
      proportion: 0.28,
    },
    {
      finding: 'Quashed',
      month: 8.0,
      year: 2022.0,
      count: 2.0,
      proportion: 0.01,
    },
    {
      finding: 'Quashed',
      month: 9.0,
      year: 2022.0,
      count: 29.0,
      proportion: 0.09,
    },
    {
      finding: 'Quashed',
      month: 10.0,
      year: 2022.0,
      count: 90.0,
      proportion: 0.27,
    },
    {
      finding: 'Quashed',
      month: 11.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.17,
    },
    {
      finding: 'Quashed',
      month: 12.0,
      year: 2022.0,
      count: 20.0,
      proportion: 0.11,
    },
    {
      finding: 'Quashed',
      month: 1.0,
      year: 2023.0,
      count: 75.0,
      proportion: 0.2,
    },
    {
      finding: 'Quashed',
      month: 2.0,
      year: 2023.0,
      count: 95.0,
      proportion: 0.27,
    },
    {
      finding: 'Quashed',
      month: 3.0,
      year: 2023.0,
      count: 16.0,
      proportion: 0.04,
    },
    {
      finding: 'Quashed',
      month: 4.0,
      year: 2023.0,
      count: 1.0,
      proportion: 0.0,
    },
    {
      finding: 'Quashed',
      month: 5.0,
      year: 2023.0,
      count: 91.0,
      proportion: 0.23,
    },
    {
      finding: 'Quashed',
      month: 6.0,
      year: 2023.0,
      count: 53.0,
      proportion: 0.24,
    },
    {
      finding: 'Quashed',
      month: 7.0,
      year: 2023.0,
      count: 54.0,
      proportion: 0.16,
    },
    {
      finding: 'Referred to Police',
      month: 7.0,
      year: 2022.0,
      count: 45.0,
      proportion: 0.22,
    },
    {
      finding: 'Referred to Police',
      month: 8.0,
      year: 2022.0,
      count: 26.0,
      proportion: 0.1,
    },
    {
      finding: 'Referred to Police',
      month: 9.0,
      year: 2022.0,
      count: 73.0,
      proportion: 0.22,
    },
    {
      finding: 'Referred to Police',
      month: 10.0,
      year: 2022.0,
      count: 72.0,
      proportion: 0.21,
    },
    {
      finding: 'Referred to Police',
      month: 11.0,
      year: 2022.0,
      count: 18.0,
      proportion: 0.08,
    },
    {
      finding: 'Referred to Police',
      month: 12.0,
      year: 2022.0,
      count: 40.0,
      proportion: 0.22,
    },
    {
      finding: 'Referred to Police',
      month: 1.0,
      year: 2023.0,
      count: 18.0,
      proportion: 0.05,
    },
    {
      finding: 'Referred to Police',
      month: 2.0,
      year: 2023.0,
      count: 90.0,
      proportion: 0.26,
    },
    {
      finding: 'Referred to Police',
      month: 3.0,
      year: 2023.0,
      count: 78.0,
      proportion: 0.2,
    },
    {
      finding: 'Referred to Police',
      month: 4.0,
      year: 2023.0,
      count: 34.0,
      proportion: 0.12,
    },
    {
      finding: 'Referred to Police',
      month: 5.0,
      year: 2023.0,
      count: 71.0,
      proportion: 0.18,
    },
    {
      finding: 'Referred to Police',
      month: 6.0,
      year: 2023.0,
      count: 17.0,
      proportion: 0.08,
    },
    {
      finding: 'Referred to Police',
      month: 7.0,
      year: 2023.0,
      count: 31.0,
      proportion: 0.09,
    },
    {
      finding: 'Suspended',
      month: 7.0,
      year: 2022.0,
      count: 55.0,
      proportion: 0.27,
    },
    {
      finding: 'Suspended',
      month: 8.0,
      year: 2022.0,
      count: 33.0,
      proportion: 0.12,
    },
    {
      finding: 'Suspended',
      month: 9.0,
      year: 2022.0,
      count: 69.0,
      proportion: 0.21,
    },
    {
      finding: 'Suspended',
      month: 10.0,
      year: 2022.0,
      count: 78.0,
      proportion: 0.23,
    },
    {
      finding: 'Suspended',
      month: 11.0,
      year: 2022.0,
      count: 39.0,
      proportion: 0.17,
    },
    {
      finding: 'Suspended',
      month: 12.0,
      year: 2022.0,
      count: 31.0,
      proportion: 0.17,
    },
    {
      finding: 'Suspended',
      month: 1.0,
      year: 2023.0,
      count: 50.0,
      proportion: 0.13,
    },
    {
      finding: 'Suspended',
      month: 2.0,
      year: 2023.0,
      count: 9.0,
      proportion: 0.03,
    },
    {
      finding: 'Suspended',
      month: 3.0,
      year: 2023.0,
      count: 91.0,
      proportion: 0.23,
    },
    {
      finding: 'Suspended',
      month: 4.0,
      year: 2023.0,
      count: 70.0,
      proportion: 0.26,
    },
    {
      finding: 'Suspended',
      month: 5.0,
      year: 2023.0,
      count: 83.0,
      proportion: 0.21,
    },
    {
      finding: 'Suspended',
      month: 6.0,
      year: 2023.0,
      count: 23.0,
      proportion: 0.11,
    },
    {
      finding: 'Suspended',
      month: 7.0,
      year: 2023.0,
      count: 88.0,
      proportion: 0.25,
    },
  ]

  return {
    '1a': chartEntries1a,
    '1b': chartEntries1b,
    '1c': chartEntries1c,
    '1d': chartEntries1d,
    '1f': chartEntries1f,
    '2a': chartEntries2a,
    '2b': chartEntries2b,
    '3a': chartEntries3a,
    '3b': chartEntries3b,
    '5a': chartEntries5a,
    '5b': chartEntries5b,
  }
}
