# Per environment values which override defaults in hmpps-manage-adjudications/values.yaml

generic-service:

  ingress:
    host: manage-adjudications.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-adjudications.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    HMPPS_MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICE_URL: https://digital.prison.service.justice.gov.uk
    PRISONER_PROFILE_SERVICE_URL: https://prisoner.digital.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api.hmpps.service.justice.gov.uk
    CURIOUS_API_URL: https://liveservices.sequation.com/sequation-virtual-campus2-api
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    SUPPORT_URL: https://support.hmpps.service.justice.gov.uk/
    PRISONER_SEARCH_API_URL: https://prisoner-search.prison.service.justice.gov.uk
    DATA_INSIGHTS_API_URL: https://adjudications-insights-api.hmpps.service.justice.gov.uk
    ADJUDICATIONS_URL: http://hmpps-manage-adjudications
    GOTENBERG_API_URL: http://hmpps-manage-adjudications-gotenberg
    FRONTEND_COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    MAINTENANCE_MODE: false


  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: digital-prison-service

gotenberg:
  replicaCount: 4
