---
# Per environment values which override defaults in hmpps-manage-adjudications/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-adjudications-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: https://api-dev.prison.service.justice.gov.uk
    DIGITAL_PRISON_SERVICE_URL: https://digital-dev.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    
  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

