---
# Per environment values which override defaults in hmpps-manage-adjudications/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-dev.hmpps.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_github_team: "hmpps-adjudications"

    modsecurity_snippet: |
      SecRuleEngine On
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE"
      # Missing User Agent Header
      SecRuleRemoveById 920320

  env:
    INGRESS_URL: "https://manage-adjudications-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    HMPPS_MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICE_URL: https://digital-dev.prison.service.justice.gov.uk
    PRISONER_PROFILE_SERVICE_URL: http://prisoner-dev.digital.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    CURIOUS_API_URL: https://testservices.sequation.net/sequation-virtual-campus2-api
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    LOCATIONS_INSIDE_PRISON_API_URL: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
    NOMIS_SYNC_PRISONER_MAPPING_API_URL: https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk
    SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
    PRISONER_SEARCH_API_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    DATA_INSIGHTS_API_URL: https://adjudications-insights-api-dev.hmpps.service.justice.gov.uk
    ADJUDICATIONS_URL: http://hmpps-manage-adjudications
    GOTENBERG_API_URL: http://hmpps-manage-adjudications-gotenberg
    FRONTEND_COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    ALERT_API_URL: https://alerts-api-dev.hmpps.service.justice.gov.uk
    MAINTENANCE_MODE: false
    ENVIRONMENT_NAME: 'DEV'
    OFFENCE_VERSION: 2

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: maintenance-alerts-non-prod-warning

gotenberg:
  replicaCount: 1
