---
# Per environment values which override defaults in hmpps-manage-adjudications/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-adjudications-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-adjudications-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    HMPPS_MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICE_URL: https://digital-dev.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_API_URL: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
    CURIOUS_API_URL: https://testservices.sequation.net/sequation-virtual-campus2-api
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
    PRISONER_SEARCH_API_URL: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
    DATA_INSIGHTS_API_URL: https://adjudications-insights-api-dev.hmpps.service.justice.gov.uk
    ADJUDICATIONS_URL: http://hmpps-manage-adjudications
    GOTENBERG_API_URL: http://hmpps-manage-adjudications-gotenberg
    MAINTENANCE_MODE: false
    V2_ENDPOINTS_FLAG: true
    FORMS_TAB_FLAG: true

  allowlist: null

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

gotenberg:
  replicaCount: 1
