name: Create test deployment

on:
  pull_request:
    types: [ synchronize, opened, reopened, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_test:
    name: Create test deployment
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    if: contains(github.event.pull_request.labels.*.name, 'test')
    secrets: inherit
    with:
      environment: 'test'
